# -*- coding: utf-8 -*-
"""LVADSUSR97.Lokesh_A_FA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A3J6uQ_h2U639SFGo0X2C2d71xRr3nTP
"""

#1
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


dat=pd.read_csv("/content/sample_data/Walmart_Dataset Python_Final_Assessment.csv")
dat
dat.head()
dat.info()
dat.describe()
numerical_data=dat[dat['column']!=dat.dtype['object']]
categorical_data=dat[dat['colunm']==dat.dtype['object']]

#2
dat.isnull()
dat.isnull().sum()
dat.dropna(inplace=True)

dat.duplicated()
dat.drop_duplicates()

#3
sales_mean=dat['Sales'].mean()
sales_median=dat['Sales'].median()
sales_std=dat['Sales'].std()
sales_mode=dat['Sales'].mode()
sales_variance=dat['Sales']
print(sales_mean)
print(sales_median)
print(sales_std)
print(sales_mode)

print('-----------')

quan_mean=dat['Quantity'].mean()
quan_median=dat['Quantity'].median()
quan_std=dat['Quantity'].std()
quan_mode=dat["Quantity"].mode()
print(quan_mean)
print(quan_median)
print(quan_std)
print(quan_mode)

print('--------')
profit_mean=dat['Profit'].mean()
profit_median=dat['Profit'].median()
profit_std=dat['Profit'].std()
profit_mode=dat['Profit'].mode()
print(profit_mean)
print(profit_median)
print(profit_std)
print(profit_mode)

#4

total_sales=dat.groupby('Category').aggregate({'Quantity':'count'})
total_sales

df=pd.DataFrame(total_sales)
df

plt.subplot(2,2,1)
plt.bar(dat['Category'],dat['Sales'])
plt.title('total sales fore each category')
plt.show()

plt.subplot(2,2,2)
plt.pie(dat['Sales'],labels=dat['Category'])
plt.show()

plt.subplot(2,2,3)
plt.scatter(dat['Profit'],dat['Sales'])
plt.title('profit vs sales')
plt.show()

plt.subplot(2,2,4)
plt.box(df['Sales'])
plt.show()

plt.subplot(2,2,4)
sns.distplot(df['Sales'],hist=True)

#5
dat.corr()

sns.heatmap(dat.corr(),annot=True,fmt='f')

#7
class walmart:

  def __init__(self,dataframe):
    self.dataframe=dataframe

  def func(self):
    ret=self.dataframe['Sales'].max()
    ret_max=self.dataframe['Sales'].idxmax()
    arr=df.loc[ret_max,dat['Category']]
    return arr,ret

  def trend(self):
    self.dataframe['Order Date']=pd.to_datetime(self.dataframe['Order Date'])



obj=walmart(dat)
print(obj.func())