# -*- coding: utf-8 -*-
"""python_internal_assessment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oLiR7yHH01BjJdn0CmcYiAVG-YEld6fs
"""

#1
length=int(input("enter the length of a rectangle"))
width=int(input("enter the width of a rectangle"))

area_of_rectangle=length*width
print("area of rectangle is:",area_of_rectangle)

#2
height=float(input("enter the height in m"))
weight=float(input("enter the weight in kg"))

bmi=weight/(height**2)
print("your bmi is:",bmi)

#3
di={}

n=int(input("enter the no of students"))

for i in range (0,n):
  name=str(input("enter student name"))
  score=float(input("enter the score"))
  di[name]=score

print(di)

#4
age=int(input("enter the age"))

if age>60:
  print("you are senior")
elif age<=60 and age>18:
  print("you are an adult")
else:
  print("you are minor")

#5
for i in range(1,50):
  if i%2==0:
    print(i,end=" ")

#6

password="12344"
i=1
while i>0:
  pas=str(input("enter the password here"))
  if(pas==password):
    print("logged in successfully")
    break
  else:
    print("wrong password try again")

  i+=1

#7
def avg(data_set):

  mean=sum(data_set)/len(data_set)
  return mean


dat_set=[1,2,4,5,6]
s=avg(dat_set)
print(s)

#8
def strings(st):

  count=0

  for i in range(0,len(st)):
    if st[i]=='a' or st[i]=='e' or  st[i]=='i' or st[i]=='o' or st[i]=='u':
      count+=1
  return count

st="latentviewanalytics"
a=strings(st)
print(a)

#9
import datetime

datetime.currdate()
datetime.time()

#10
a=name
b=age



try:
  c=a+b
  print(c)
except:
  print("exception error")

#11
a=name
b=age



try:
  c=a+b
  print(c)
except ValueError:
  print("value error")

#12

a=10
b=0

try:
  c=a/b
  print(c)
except:
  print("denominator cannot be zero")

#13
mywritefile=open("/content/python.txt",'w')

print(mywritefile.write("hello python!"))

#14
readfile=open("/content/python.txt",'r')
print(readfile.read())

#15
readfile.append()